- name: Check if Homebrew is installed
  command: brew --version
  register: brew_version
  changed_when: false
  failed_when: false

- name: Install Homebrew
  shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  when: brew_version.failed

- name: Update Homebrew
  homebrew: update_homebrew=yes
  
- name: Get list of installed Homebrew packages
  command: brew list
  changed_when: false
  register: homebrew_packages_installed

- name: Install Homebrew packages
  homebrew: >
    name={{ item.name }}
    state={{ item.state | default('latest') }}
    install_options={{
      item.install_options | default() | join(',')
      if item.install_options is not string
      else item.install_options
    }}
  with_items: "{{ homebrew_packages }}"
  when: item.name not in homebrew_packages_installed.stdout_lines

- name: Install Homebrew cask packages
  homebrew_cask: name={{ item.name }} state={{ item.state | default('installed') }}
  with_items: "{{homebrew_cask_packages}}"
  
